name: MasterDeployCI
on:
    push:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14.x]
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install Packages
              run: |
                  npm install
                  npm test
            - name: Deploy to GitHub Pages
              # You may pin to the exact commit or the version.
              # uses: JamesIves/github-pages-deploy-action@0f24da7de3e7e135102609a4c9633b025be8411b
              uses: JamesIves/github-pages-deploy-action@4.1.5
              with:
                  branch: master
                  # The folder in your repository that you want to deploy. If your build script compiles into a directory named build you would put it here. Folder paths cannot have a leading / or ./. If you wish to deploy the root directory you can place a . here.
                  folder: root
