name: MasterDeployCI
on:
    push:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14.x]
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install Packages
              run: |
                  npm install
                  npm test
            - name: Deploy to GitHub Pages
              run: |
                  git config --global user.email ${{secrets.GITHUB_EMAIL}}
                  git config --global user.name ${{secrets.GITHUB_USERNAME}}
                  git remote set-url origin ${{secrets.GITHUB_ACCESS_TOKEN}}@github.com/${{secrets.GITHUB_USERNAME}}/frontend-tinder.git
                  npm run deploy
